name: sajuilogin
main: com.oxh.login.Main
version: 1.0.0
api-version: 1.20
commands:
  captcha:
    description: Responder captcha
    usage: /captcha <resultado>
  login:
    description: Ejecuta login con contrase침a
    usage: /login <contrase침a>
  premiumconfirmar:
    description: Confirma activaci칩n de premium
    usage: /premiumconfirmar
  register:
    description: Registrar jugador
    usage: /register <contrase침a>
